### ISSUE TITLE
NPM installs discord.js version 13 but not 12

### ISSUE THREAD

**Issue by yuki0418** [flexphere/discord-speecher#24]
Discord.js has released version 13 which changes a lot and cause version error because version in this repo is 12. Need to fix to version 12

**Comment by takoyaro** [comment]
As of 71acc2b5e98f895cf9e2a11dba55185e4b84c82d we are using [Discord.js 14.9.0](https://github.com/flexphere/discord-speecher/blob/71acc2b5e98f895cf9e2a11dba55185e4b84c82d/package-lock.json#L1157)
